"""followers

Revision ID: 036af739b21b
Revises: 241be06927df
Create Date: 2021-03-31 10:55:59.174547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036af739b21b'
down_revision = '241be06927df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
