"""new fields in user model

Revision ID: 241be06927df
Revises: 696a6e90b5b2
Create Date: 2021-03-26 13:42:31.795344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241be06927df'
down_revision = '696a6e90b5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
